name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
        # - name: Use Node.js ${{ matrix.node-version }}
        #   uses: actions/setup-node@v1
        #   with:
        #     node-version: ${{ matrix.node-version }}
      - run: npm install
        working-directory: website
      - run: npm run build --if-present
        working-directory: website
      - name: log untrusted output
        run: |

        # disable command workflow processing
        echo "::stop-commands::`echo -n ${{ github.token }} | sha256sum | head -c 64`"
 
        # log untrusted output
        echo "untrusted output"
 
        # enable workflow command processing
        echo "::`echo -n ${{ github.token }} | sha256sum | head -c 64`::"
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: website/dist # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
